name: ca_learning

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8000:8000"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=8000
      - SERVICE_DEBUG=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    environment:
      - SERVICE_DEBUG=true
      - PYTHONPATH=/app
    volumes:
      - ./:/app:cached
      - pip-cache:/root/.cache/pip

volumes:
  pip-cache: